### ISSUE TITLE
POST /api/v1/ads/   отправленный без обязательного  тела, возвращает 200

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#169]
curl --location --request POST 'https://sunnyekb.ru/api/v1/ads' \
--data ''
Отправить POST /api/v1/ads/  без обязательного  тела

ОР: 400
ФР: 200

**Comment by PentiukPavel** [comment]
Возвращаемый ответ:
{
    "title": [
        "Обязательное поле."
    ],
    "description": [
        "Обязательное поле."
    ],
    "price": [
        "Обязательное поле."
    ],
    "category_id": [
        "Обязательное поле."
    ]
}
