### ISSUE TITLE
POST /api/v1/ads/   Тело возвращаемого ответа не соотв требованиям 

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#170]
curl --location 'https://sunnyekb.ru/api/v1/ads' \
--header 'Content-Type: application/json' \
--data '{
  "title": "Ботинки",
  "description": "Зимние ботинки",
  "price": "1000.00",
  "condition": "Б/у",
  "category_id": 4
}'

Отправить  POST /api/v1/ads/   с телом

ОР: Ожидаем тело ответа  
:{
  "title": "Ботинки",
  "description": "Зимние ботинки",
  "price": "1000.00",
  "condition": "Б/у",
  "category_id": 4
}
ФР:
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}

**Comment by PentiukPavel** [comment]
Ошибка была в документации. От сервера должен приходить ответ с пагинацией. Документацию поправил.
