### ISSUE TITLE
POST/api/v1/change-password при пароле и подтверждении пароля не соответствующим друг другу ожид 400, получаем 401 

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#171]
curl --location 'https://sunnyekb.ru/api/v1/change-password' \
--header 'Content-Type: application/json' \
--data '{
  "current_password": "superPuper",
  "new_password": "superPuper2",
  "confirmation": "superer"
}'

Отправить POST/api/v1/change-password  с новым паролем  и подтверждением пароля не соответствующими друг другу
ОР: 400  Bad Request 
            "Password and confirmation do not match"
ФР: 401 Unathorized 
            "Учетные данные не были предоставлены."

**Comment by PentiukPavel** [comment]
Это значит, что закончился срок действия access token и нужно его обновить.
Я проверил, при вводе несовпадающих паролей возвращает 400.

**Comment by VarLimit6** [comment]
<html>
<body>

400 | Error: Bad RequestResponse bodyDownload{   "password": [     "Password and confirmation do not match"   ] }
-- | --

</body>
</html>

Проверена последовательная смена паролей.
Смена пароля и логин/логаут.
Все в swagger

**Comment by VarLimit6** [comment]
Закрываю

**Comment by VarLimit6** [comment]
-

**Comment by VarLimit6** [comment]
400 | Error: Bad RequestResponse bodyDownload{ "password": [ "Password and confirmation do not match" ] } -- | --
Проверена последовательная смена паролей.
Смена пароля и логин/логаут.
Все в swagger
