### ISSUE TITLE
GET /api/v1/adimage/{id}  параметр id не реализован как обязательный

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#177]
1. curl --location --globoff 'https://sunnyekb.ru/api/v1/adimage/{id}/'
Сформировать и отправить запрос в постман.

ОР: 400
ФР: 404  Not found
{
    "detail": "Страница не найдена."
}

**Comment by PentiukPavel** [comment]
Мне кажется, что такой запрос должен обрабатываться как 404.
У сервера есть ручка api/v1/adimage/<int: id>
Фактически он получает api/v1/adimage/%7Bid%7D/
"%7Bid%7D" не является числом и поэтому он считает, что обращаются к несуществующей странице.
