### ISSUE TITLE
GET /api/v1/ads/  при отл от integer значениях category_id, возвращает 500

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#182]
curl --location 'https://sunnyekb.ru/api/v1/ads?category_id=%20'

Согласно  описанию для получения списка необходимо указать category_id, при отсутствии параметра - пустой список.
category_id - integer

1. category_id= пробел
2.  category_id= 1,2
3.  category_id= 1.2
4.  category_id= н 
5.  category_id=f

ОР: 400
ФР: Server Error (500)

**Comment by PentiukPavel** [comment]
Поправил.
