### ISSUE TITLE
GET/api/v1/ads/  Для параметра category_id= отрицательного, возвращает 200

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#183]
curl --location 'https://sunnyekb.ru/api/v1/ads?category_id=-4'

Согласно  описанию для получения списка необходимо указать category_id, при отсутствии параметра - пустой список.
category_id  integer

При заданном  category_id= отрицательным число (-4)

ОР: 400
ФР: 200

**Comment by PentiukPavel** [comment]
Попраил.

**Comment by VarLimit6** [comment]
Исправлено.
{
    "detail": "Параметр должен быть положительным числом."
}
curl --location 'https://sunnyekb.ru/api/v1/ads?category_id=-1'
