### ISSUE TITLE
GET /api/v1/types При  title = '%' , возвращает 400

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#197]
curl --location 'https://sunnyekb.ru/api/v1/types?title=%27%%27'
Задать title = '%'

ОР: 200 и соответствующие категории, в нашем случае пустой список
ФР: 400

**Comment by PentiukPavel** [comment]
Готово. Url для title = '%' - https://sunnyekb.ru/api/v1/types/?title=%27%25%27
