### ISSUE TITLE
POST /api/v1/password_reset возвращает 500 

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#204]
curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/password_reset/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: Dme5aK6fMgWcLy6FRXiZtI8jjXn1T3l0Vd4fFYAXztNVaeshzaFFg7EFnJ647yav' \
  -d '{
  "email": "tikhonova@inbox.ru"
}'

1. Зарегистрировать пользователя с сущ почтой.
2. POST /api/v1/password_reset  с этой почтой.

ОР: 200 на почту придет ссылка для смены пароля.

ФР: 500
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>

responce headers:
<html>
<body>
<div style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(73, 204, 144, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
access-control-allow-credentials: true  access-control-allow-origin: https://sunnyekb.ru  access-control-expose-headers: Content-Type,X-CSRFToken  connection: keep-alive  content-length: 145  content-type: text/html; charset=utf-8  cross-origin-opener-policy: same-origin  date: Sun,15 Dec 2024 13:31:25 GMT  referrer-policy: same-origin  server: nginx/1.21.3  vary: origin  x-content-type-options: nosniff  x-csrftoken: s10kFoESXn1TzQwMSnxQXzGweWTdoFZF  x-frame-options: DENY
--

</div><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; margin: 10px 0px 5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(73, 204, 144, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Responses</h4>
</body>
</html>

**Comment by PentiukPavel** [comment]
Ошибка исправлена.

**Comment by VarLimit6** [comment]
Попытка смены пароля, при указании адресов mail.ru, icloud.com, gmail.com успешна (200 ok). Письмо на заданную почту приходит

**Comment by VarLimit6** [comment]
Попытка смены пароля, при указании адресов mail.ru, icloud.com, gmail.com успешна (200 ok). Письмо на заданную почту приходит

**Comment by VarLimit6** [comment]
Попытка смены пароля, при указании адресов mail.ru, icloud.com, gmail.com успешна (200 ok). Письмо на заданную почту приходит
