### ISSUE TITLE
Требования к паролю не соотв тех заданию

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#210]
ОР: По техническому заданию: "пароль (минимум 8 символов и максимум 25 символов, специальные требования (в пароле должны присутствовать заглавная, строчная буквы, цифра и специальный символ) поле пароля должно быть замаскировано)."
ФР: позволяет задать пароль из одного числа

1. POST /api/v1/registry   
Регистрация пользователя

curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/registry/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: dZcID2AGQjniv4Q5voGzyXOxgpxSGBVlvQ2S8g4oDwe1UKcHdB3flmkTkbgVU6KQ' \
  -d '{
  "username": "user3",
  "email": "van@inbox.ru",
  "phone": "+79000000000",
  "password": "1",
  "confirmation": "1"
}'

2. POST /api/v1/login/
curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/login/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: dZcID2AGQjniv4Q5voGzyXOxgpxSGBVlvQ2S8g4oDwe1UKcHdB3flmkTkbgVU6KQ' \
  -d '{
  "email": "van@inbox.ru",
  "password": "1"
}'
3. Смена пароля
curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/change-password/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: dZcID2AGQjniv4Q5voGzyXOxgpxSGBVlvQ2S8g4oDwe1UKcHdB3flmkTkbgVU6KQ' \
  -d '{
  "current_password": "11111",
  "new_password": "1",
  "confirmation": "1"
}'

**Comment by VarLimit6** [comment]
1) POST /api/v1/registry
Регистрация пользователя

ОР: По техническому заданию: "пароль (минимум 8 символов и максимум 25 символов, специальные требования (в пароле должны присутствовать заглавная, строчная буквы, цифра и специальный символ) поле пароля должно быть замаскировано)."
ФР: позволяет создать пароль более 25 символов;
      спецсимвол не является обязательным;
      возможно задать либо строчную либо заглавную;
      цифры не являются обязательным

**Comment by PentiukPavel** [comment]
Исправлено.
