### ISSUE TITLE
PUT /api/v1/users/{id} Тело ответа не соответствует документации 

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#220]
curl -X 'PUT' \
  'https://sunnyekb.ru/api/v1/users/51/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: 2o282EW9ez6b09S4MjLW2pyw5XcU9Ln3M6pEfzIZu3vOufN6i9N6Gmm09bzvds25' \
  -d '{
  "username": "User8",
  "first_name": "FirstName",
  "last_name": "LastName",
  "phone": "+79123450000"
}'

ОР: 
{
  "username": "Some_username",
  "first_name": "Some_name",
  "last_name": "Some_name",
  "phone": "+79000000000"
}
ФР: тело ответа содержит не требуемые id, email, role, avatar.  "phone" выше "last_name".  
{
  "id": 51,
  "username": "User8",
  "email": "example8@example.com",
  "phone": "+79123450000",
  "first_name": "FirstName",
  "last_name": "LastName",
  "role": "user",
  "avatar": null
}

**Comment by PentiukPavel** [comment]
В ответе приходит полная информация о пользователе.
