### ISSUE TITLE
POST /api/v1/change-password Поправить сообщение при смене пароля на текущий

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#227]
curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/change-password/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: RfSrm5ZFDp7uvBTLjlm6hZCDLel9sCqgBXfXz0LvTTw7ZHONPbogVWq7PsIKwj5i' \
  -d '{
  "current_password": "12345",
  "new_password": "12345",
  "confirmation": "12345"
}'

Залогиниться.
Сменить пароль на текущий.

ОР: Желательно , если его будут видеть заменить на New password is the same as the latest/as last one
ФР: {
  "password": [
    "New password is the same as old one"
  ]
}

**Comment by PentiukPavel** [comment]
Поправил.
