### ISSUE TITLE
POST/api/v1/change-password Не формировать сообщения о выборе пароля как факт/не использовать в подсказках имена переменных

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#229]
1. POST/api/v1/change-password
 ФР: При 400 сообщение носит характер факта - "Введённый пароль состоит только из цифр."
ОР: Сообщение будет  носить характер подсказки: "Пароль должен содержать цифры, буквы латинского и  русского алфавитов, ..."

2. POST  /api/v1/registry
ФР:{
  "username": [
    "Пользователь с таким username уже существует."
  ]
}
ОР: Сообщение будет  носить характер подсказки. Такой псевдоним/пользователь уже существует. Замените имя пользователя.

**Comment by PentiukPavel** [comment]
Готово.
