### ISSUE TITLE
POST/api/v1/verify-registration/ Для не подтвержденного пользователя-  возвращает 500 

### ISSUE THREAD

**Issue by VarLimit6** [SunnyEkb/sunny_backend#237]
curl -X 'POST' \
  'https://sunnyekb.ru/api/v1/verify-registration/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: CKlUa1cRGzBDa2dH0CL5liOAwkdPKPnuwNDHlNRiHq2pvF3ZURLJePRDjfpD3hjU' \
  -d '{
  "token": "84cddda3-eef1-460d-8a2e-5f48e8d923e3"
}'

1. Зарегистрировать пользователя (сваггер).
2.  В полученном письме по ссылке не подтверждать почту.
3. Вызвать в сваггере POST/api/v1/verify-registration
 

ОР: 401/400
ФР: 500

**Comment by PentiukPavel** [comment]
Поправил.
